# Generated by Django 5.1.6 on 2025-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzrpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
